### ISSUE TITLE
Implement Runion-01 "Characters per line runion"

### ISSUE THREAD

**Issue by graphicore** [graphicore/varla-varfo#11]
@dberlow wrote in an Email:
> Here is some #commented # pseudo code […]
>
```
#Runion 0 #

# how long is the text? #

get total string length = string-ens

if >= 365

# sounds bigger than a caption

Goto Runion1

Else

#shorter text strings later#

#Runion 1#

#Characters per line runion#

get line length in em*2  #en is closer to l.c. glyph count #

if line length </= 65en, compose

else

#divide to 2 columns

if en length/2 <= 65en compose

else

#divide to 3 columns

if en length/2 > 50en <65en compose

else

#divide to 4 columns

if en length/2 > 40en, compose

else

#add padding, we don’t use 5-columns;) #


#Runion 2#

Latin, Greek Cyrillic padding

padding = x

x/5 * 3 = left pad

x/5 * 2 = right pad

```

There's an initial implementation now, but it has open questions that need resolution. I'll comment below.

**Comment by graphicore** [comment]
Besides me ignoring the nature of Runions for the moment, I also took some liberty in the interpretation of the pseudo-code above.

The implementation is data driven, the idea is that we may want to change details in other situations or for other languages. The main variables are `max-number-of-columns` and per column `min-line-length`,  `max-line-length`, and `column-gap-width`:

```js
    // here 4 entries = max 4 columns
    // [minLineLength, maxLineLength, columnGap] in en
    // Note that column gap could also be more flexible depending on the actual
    // column size, but that would change the algorithm.
    var columnConfig = [
        [ 0, 65, 0]  // 1
      , [33, 65, 3] // 2
      , [33, 50, 2.5] // 3
      , [33, 40, 2] // 4
    ];
```

Here's the actual implementation:

https://github.com/graphicore/varla-varfo/blob/272993fdab1683355165b64189dbc32ccbf720f6/explorations/wikipedia/js/main.mjs#L290-L329

It starts from the 1-column layout and moves up to the 4-column layout, if the available space can't satisfy the column min/max restrictions. In this first pass, no padding is applied.

In the second pass, it moves down from the 4-column layout to the 1-column layout, applying the max-line-length and padding for the rest of the available space. If there's not enough space less columns are tried. The ultimate case is the 1 column layout with padding.

I chose this implementation, because in the pseudo code, it would have been possible to have e.g. ultra-narrow lines in 4-column layout but with padding. So, now lines are not shorter than 33en, unless there is really not much space then we end up with a 1-column layout.

I hope I still captured the main intent of the algorithm, which, I think, is to increase the number columns but decrease the max-line length as more space becomes available.

---

(This may become another issue.)
Other values we could (but do not) determine from this, as we know the `line-length`, are the currently static:

https://github.com/graphicore/varla-varfo/blob/272993fdab1683355165b64189dbc32ccbf720f6/explorations/wikipedia/main.css#L700-L711

**Comment by dberlow** [comment]
“runion” - a piece of software code that addresses all of the conditions that may arise requiring change to the Typographic specification for a run of text.

On Apr 7, 2021, at 2:12 PM, Lasse Fister ***@***.***> wrote:

﻿
Besides me ignoring the nature of Runions for the moment, I also took some liberty in the interpretation of the pseudo-code above.

The implementation is data driven, the idea is that we may want to change details in other situations or for other languages. The main variables are max-number-of-columns and per column min-line-length, max-line-length, and column-gap-width:

    // here 4 entries = max 4 columns
    // [minLineLength, maxLineLength, columnGap] in en
    // Note that column gap could also be more flexible depending on the actual
    // column size, but that would change the algorithm.
    var columnConfig = [
        [ 0, 65, 0]  // 1
      , [33, 65, 3] // 2
      , [33, 50, 2.5] // 3
      , [33, 40, 2] // 4
    ];
Here's the actual implementation:

https://github.com/graphicore/varla-varfo/blob/272993fdab1683355165b64189dbc32ccbf720f6/explorations/wikipedia/js/main.mjs#L290-L329

It starts from the 1-column layout and moves up to the 4-column layout, if the available space can't satisfy the column min/max restrictions. In this first pass, no padding is applied.

In the second pass, it moves down from the 4-column layout to the 1-column layout, applying the max-line-length and padding for the rest of the available space. If there's not enough space less columns are tried. The ultimate case is the 1 column layout with padding.

I chose this implementation, because in the pseudo code, it would have been possible to have e.g. ultra-narrow lines in 4-column layout but with padding. So, now lines are not shorter than 33en, unless there is really not much space then we end up with a 1-column layout.

I hope I still captured the main intent of the algorithm, which, I think, is to increase the number columns but decrease the max-line length as more space becomes available.

(This may become another issue.)
Other values we could (but do not) determine from this, as we know the line-length, are the currently static:

https://github.com/graphicore/varla-varfo/blob/272993fdab1683355165b64189dbc32ccbf720f6/explorations/wikipedia/main.css#L700-L711
