### ISSUE TITLE
Question on calibrate scale difference

### ISSUE THREAD

**Issue by mikedidthis** [graphicore/varla-varfo#21]
Hey @graphicore!

Firstly I want to thank you for the excellent documentation / work on absolute length units! 

I have a question about the scale factor value generated by the two calibration tool examples:

### [Absolute Unit Evaluation](https://graphicore.github.io/varla-varfo/explorations/techniques/absolute_units_evaluation)

![image](https://user-images.githubusercontent.com/910412/144222314-1748cc61-9bfe-418c-8f7b-b51e055d04ac.png)

If I input `10cm` the scale factor is `1`. This seems correct based on `CSS Value / Real World Value`.

### [Calibrate CSS](https://graphicore.github.io/varla-varfo/explorations/calibrate/)

![image](https://user-images.githubusercontent.com/910412/144222465-ddcc6041-363c-4fe6-8ecc-9cc0816d64a0.png)

If I input `10cm` the scale factor is `1.00125`. This seems off based on `CSS Value / Real World Value` and I expected the value to be `1`.

Please let me know if I missed anything or if I can help in anyway!

**Comment by mikedidthis** [comment]
Closing in favour of https://github.com/graphicore/varla-varfo/discussions/22

**Comment by graphicore** [comment]
Hi @mikedidthis, thanks for reporting this! I answer in the issue, as this is indeed a bug.

> If I input 10cm the scale factor is 1.00125. This seems off based on CSS Value / Real World Value and I expected the value to be 1.

That is correct! I fixed it in b10ba5d

The initial problem was, that I used the `Element.clientHeight` and `Element.clientWidth` DOM properties, to read the current state of the elements, but [MDN explains](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight) that rounding is happening on these properties:

> **Note:** This property will round the value to an integer. If you need a fractional value, use [`element.getBoundingClientRect()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect). 

Now, with that change, I get a small precision error, but not nearly as big as previously:

![Screenshot from 2021-12-01 13-30-43](https://user-images.githubusercontent.com/393132/144235214-d8aa0c9f-74e3-48e8-a4ce-f6cefb0ae7b3.png)

Instead of `1` the value is now `0.9999927406311034`.

This happens because the value is calculated going via a transformation to `px` units, with some effort, some of these transformations could be averted. However, for the correctness in this case the precision error is negligible.
